use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'BasicLibrary-OC_Example' do
  pod 'BasicLibrary-OC', :path => '../'

  target 'BasicLibrary-OC_Tests' do
    inherit! :search_paths

    
  end
end
